# Generated by Django 5.0 on 2024-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
